# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeCurrencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('currencies', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('currencies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency_rates.ExchangeCurrencies')),
            ],
        ),
    ]
