# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangecurrencies',
            options={'verbose_name': 'Exchange Currencies Pair', 'verbose_name_plural': 'Exchange Currencies Pairs'},
        ),
        migrations.AlterModelOptions(
            name='exchangerates',
            options={'verbose_name': 'Exchange rate', 'verbose_name_plural': 'Exchange rates'},
        ),
        migrations.AlterField(
            model_name='exchangecurrencies',
            name='currencies',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
